package com.translator.jdbc;

import com.translator.core.DialectType;
import com.translator.core.SqlTranslator;
import com.translator.core.config.TranslationConfig;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.sql.*;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.Executor;

/**
 * 翻译连接实现。
 * 包装真实数据库连接，在创建 Statement 时注入翻译功能。
 */
public class TranslatorConnection implements Connection, AutoCloseable {

    private static final Logger log = LoggerFactory.getLogger(TranslatorConnection.class);

    private final Connection realConnection;
    private final DialectType sourceDialect;
    private final DialectType targetDialect;
    private final SqlTranslator translator;

    public TranslatorConnection(Connection realConnection,
                                DialectType sourceDialect,
                                DialectType targetDialect) {
        this(realConnection, sourceDialect, targetDialect, null);
    }

    public TranslatorConnection(Connection realConnection,
                                DialectType sourceDialect,
                                DialectType targetDialect,
                                TranslationConfig config) {
        this.realConnection = realConnection;
        this.sourceDialect = sourceDialect;
        this.targetDialect = targetDialect;
        this.translator = new SqlTranslator(sourceDialect, targetDialect, config);
    }

    /**
     * 获取 SQL 翻译器。
     */
    public SqlTranslator getTranslator() {
        return translator;
    }

    /**
     * 翻译 SQL 语句。
     */
    public String translateSql(String sql) {
        return translator.translate(sql);
    }

    // ===== Statement 创建 =====

    @Override
    public Statement createStatement() throws SQLException {
        return new TranslatorStatement(realConnection.createStatement(), this);
    }

    @Override
    public PreparedStatement prepareStatement(String sql) throws SQLException {
        String translatedSql = translateSql(sql);
        log.debug("PreparedStatement 转换: [{}] → [{}]", sql, translatedSql);
        return new TranslatorPreparedStatement(
                realConnection.prepareStatement(translatedSql), this, sql, translatedSql);
    }

    @Override
    public CallableStatement prepareCall(String sql) throws SQLException {
        String translatedSql = translateSql(sql);
        return new TranslatorCallableStatement(
                realConnection.prepareCall(translatedSql), this, sql, translatedSql);
    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency)
            throws SQLException {
        return new TranslatorStatement(
                realConnection.createStatement(resultSetType, resultSetConcurrency), this);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType,
                                              int resultSetConcurrency) throws SQLException {
        String translatedSql = translateSql(sql);
        return new TranslatorPreparedStatement(
                realConnection.prepareStatement(translatedSql, resultSetType, resultSetConcurrency),
                this, sql, translatedSql);
    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency,
                                     int resultSetHoldability) throws SQLException {
        return new TranslatorStatement(
                realConnection.createStatement(resultSetType, resultSetConcurrency,
                        resultSetHoldability), this);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType,
                                              int resultSetConcurrency,
                                              int resultSetHoldability) throws SQLException {
        String translatedSql = translateSql(sql);
        return new TranslatorPreparedStatement(
                realConnection.prepareStatement(translatedSql, resultSetType, resultSetConcurrency,
                        resultSetHoldability),
                this, sql, translatedSql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys)
            throws SQLException {
        String translatedSql = translateSql(sql);
        return new TranslatorPreparedStatement(
                realConnection.prepareStatement(translatedSql, autoGeneratedKeys),
                this, sql, translatedSql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int[] columnIndexes)
            throws SQLException {
        String translatedSql = translateSql(sql);
        return new TranslatorPreparedStatement(
                realConnection.prepareStatement(translatedSql, columnIndexes),
                this, sql, translatedSql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, String[] columnNames)
            throws SQLException {
        String translatedSql = translateSql(sql);
        return new TranslatorPreparedStatement(
                realConnection.prepareStatement(translatedSql, columnNames),
                this, sql, translatedSql);
    }

    @Override
    public CallableStatement prepareCall(String sql, int resultSetType,
                                         int resultSetConcurrency) throws SQLException {
        String translatedSql = translateSql(sql);
        return new TranslatorCallableStatement(
                realConnection.prepareCall(translatedSql, resultSetType, resultSetConcurrency),
                this, sql, translatedSql);
    }

    @Override
    public CallableStatement prepareCall(String sql, int resultSetType,
                                         int resultSetConcurrency,
                                         int resultSetHoldability) throws SQLException {
        String translatedSql = translateSql(sql);
        return new TranslatorCallableStatement(
                realConnection.prepareCall(translatedSql, resultSetType, resultSetConcurrency,
                        resultSetHoldability),
                this, sql, translatedSql);
    }

    // ===== 委托方法 =====

    @Override
    public String nativeSQL(String sql) throws SQLException {
        return translateSql(sql);
    }

    @Override
    public void setAutoCommit(boolean autoCommit) throws SQLException {
        realConnection.setAutoCommit(autoCommit);
    }

    @Override
    public boolean getAutoCommit() throws SQLException {
        return realConnection.getAutoCommit();
    }

    @Override
    public void commit() throws SQLException {
        realConnection.commit();
    }

    @Override
    public void rollback() throws SQLException {
        realConnection.rollback();
    }

    @Override
    public void close() throws SQLException {
        realConnection.close();
    }

    @Override
    public boolean isClosed() throws SQLException {
        return realConnection.isClosed();
    }

    @Override
    public DatabaseMetaData getMetaData() throws SQLException {
        return realConnection.getMetaData();
    }

    @Override
    public void setReadOnly(boolean readOnly) throws SQLException {
        realConnection.setReadOnly(readOnly);
    }

    @Override
    public boolean isReadOnly() throws SQLException {
        return realConnection.isReadOnly();
    }

    @Override
    public void setCatalog(String catalog) throws SQLException {
        realConnection.setCatalog(catalog);
    }

    @Override
    public String getCatalog() throws SQLException {
        return realConnection.getCatalog();
    }

    @Override
    public void setTransactionIsolation(int level) throws SQLException {
        realConnection.setTransactionIsolation(level);
    }

    @Override
    public int getTransactionIsolation() throws SQLException {
        return realConnection.getTransactionIsolation();
    }

    @Override
    public SQLWarning getWarnings() throws SQLException {
        return realConnection.getWarnings();
    }

    @Override
    public void clearWarnings() throws SQLException {
        realConnection.clearWarnings();
    }

    @Override
    public Map<String, Class<?>> getTypeMap() throws SQLException {
        return realConnection.getTypeMap();
    }

    @Override
    public void setTypeMap(Map<String, Class<?>> map) throws SQLException {
        realConnection.setTypeMap(map);
    }

    @Override
    public void setHoldability(int holdability) throws SQLException {
        realConnection.setHoldability(holdability);
    }

    @Override
    public int getHoldability() throws SQLException {
        return realConnection.getHoldability();
    }

    @Override
    public Savepoint setSavepoint() throws SQLException {
        return realConnection.setSavepoint();
    }

    @Override
    public Savepoint setSavepoint(String name) throws SQLException {
        return realConnection.setSavepoint(name);
    }

    @Override
    public void rollback(Savepoint savepoint) throws SQLException {
        realConnection.rollback(savepoint);
    }

    @Override
    public void releaseSavepoint(Savepoint savepoint) throws SQLException {
        realConnection.releaseSavepoint(savepoint);
    }

    @Override
    public Clob createClob() throws SQLException {
        return realConnection.createClob();
    }

    @Override
    public Blob createBlob() throws SQLException {
        return realConnection.createBlob();
    }

    @Override
    public NClob createNClob() throws SQLException {
        return realConnection.createNClob();
    }

    @Override
    public SQLXML createSQLXML() throws SQLException {
        return realConnection.createSQLXML();
    }

    @Override
    public boolean isValid(int timeout) throws SQLException {
        return realConnection.isValid(timeout);
    }

    @Override
    public void setClientInfo(String name, String value) throws SQLClientInfoException {
        realConnection.setClientInfo(name, value);
    }

    @Override
    public void setClientInfo(Properties properties) throws SQLClientInfoException {
        realConnection.setClientInfo(properties);
    }

    @Override
    public String getClientInfo(String name) throws SQLException {
        return realConnection.getClientInfo(name);
    }

    @Override
    public Properties getClientInfo() throws SQLException {
        return realConnection.getClientInfo();
    }

    @Override
    public Array createArrayOf(String typeName, Object[] elements) throws SQLException {
        return realConnection.createArrayOf(typeName, elements);
    }

    @Override
    public Struct createStruct(String typeName, Object[] attributes) throws SQLException {
        return realConnection.createStruct(typeName, attributes);
    }

    @Override
    public void setSchema(String schema) throws SQLException {
        realConnection.setSchema(schema);
    }

    @Override
    public String getSchema() throws SQLException {
        return realConnection.getSchema();
    }

    @Override
    public void abort(Executor executor) throws SQLException {
        realConnection.abort(executor);
    }

    @Override
    public void setNetworkTimeout(Executor executor, int milliseconds) throws SQLException {
        realConnection.setNetworkTimeout(executor, milliseconds);
    }

    @Override
    public int getNetworkTimeout() throws SQLException {
        return realConnection.getNetworkTimeout();
    }

    @Override
    public <T> T unwrap(Class<T> iface) throws SQLException {
        if (iface.isAssignableFrom(getClass())) {
            return iface.cast(this);
        }
        return realConnection.unwrap(iface);
    }

    @Override
    public boolean isWrapperFor(Class<?> iface) throws SQLException {
        return iface.isAssignableFrom(getClass()) || realConnection.isWrapperFor(iface);
    }
}
