# MySQL Proxy 默认配置
proxy:
  port: 3306
  auth:
    user: root
    password: proxy_password
backends:
  - name: tpch
    dialect: POSTGRESQL
    jdbc-url: jdbc:postgresql://127.0.0.1:5432/mydb?currentSchema=tpch
    username: sdtpu
    password: pg_password
    max-pool-size: 10
    min-idle: 2
  - name: tpcc
    dialect: POSTGRESQL
    jdbc-url: jdbc:postgresql://127.0.0.1:5432/mydb?currentSchema=tpcc
    username: sdtpu
    password: pg_password
    max-pool-size: 10
    min-idle: 2
translation:
  keyword-case: UPPER
  identifier-case: LOWER
